### ISSUE TITLE
Error while running sample script

### ISSUE THREAD

**Issue by mawic** [eriknyquist/ptttl#1]
Hi,
I wanted to run the sample. But I get the following error:
`Traceback (most recent call last):
  File "ptttl/ptttl_audio_encoder.py", line 87, in <module>
    ptttl_to_mp3(ptttl_data, sys.argv[2], 0.5, tones.SINE_WAVE)
  File "ptttl/ptttl_audio_encoder.py", line 71, in ptttl_to_mp3
    ptttl_to_wav(ptttl_data, wavfile, amplitude, wavetype)
  File "ptttl/ptttl_audio_encoder.py", line 67, in ptttl_to_wav
    samples = _generate_wav_file(data, amplitude, wavetype, wav_filename)
  File "ptttl/ptttl_audio_encoder.py", line 57, in _generate_wav_file
    Mixer(SAMPLE_RATE, amplitude).mix(filename, samples)
TypeError: mix() takes 1 positional argument but 3 were given`

Then I tried to fix it by myself. I had the idea to replace this line:
`Mixer(SAMPLE_RATE, amplitude).mix(filename, samples)`
by
`Mixer(SAMPLE_RATE, amplitude).write_wav(filename, samples)`

But it also doesn't work. Any idea how to fix it? It tested the code on Windows 10 and Linux.
Thanks!

**Comment by eriknyquist** [comment]
Hey,

I haven't touched this code for a while, I'll take a look later tonight and
fix it.

Thanks,
Erik

**Comment by eriknyquist** [comment]
It should be fixed now. Note you will also need to download the newest
version of the 'tones' library (1.0.1), I just updated that too.

**Comment by mawic** [comment]
Hi Erik,
thanks for the quick fix. I got it running. However, it fixed some lines of code in tones. I assume you forgot to push 1.0.1.
This are my new code in mixer.py
```  def write_wav(self, filename, sampledata=None):
        """
        Mixes all tracks into a single stream of samples and writes to a
        .wav audio file

        :param str filename: name of file to write
        """

        f = wave.open(filename, 'w')

        if sampledata is None:
            sampledata = self.mix().serialize()

        f.setparams((tones.NUM_CHANNELS, tones.DATA_SIZE, self._rate,
            int(len(sampledata) / 2), "NONE", "Uncompressed"))

        f.writeframes(sampledata)
        f.close()```

**Comment by eriknyquist** [comment]
OK, glad you got it working. 1.0.1 is up on pypi
https://pypi.org/project/tones/

and that code you said you added is actually already in there
https://github.com/eriknyquist/tones/blob/master/tones/mixer.py#L401

not sure what went wrong.
